[package]
name = "url"
version = "0.1.0"
authors = ["Yagiz Nizipli <yagiz@nizipli.com"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.56"
wasm-bindgen = "0.2.79"

[dev-dependencies]
criterion = "0.3.5"