name: rust test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install wasm-pack
        run: cargo install wasm-pack
        working-directory: rust
      - name: Cargo Clippy
        run: cargo clippy
        working-directory: rust
      - name: Cargo Format
        run: cargo fmt --check
        working-directory: rust
      - name: Build
        run: cargo build
        working-directory: rust
      - name: Run tests
        run: cargo test
        working-directory: rust
      - name: Run wasm tests
        run: wasm-pack test --node
        working-directory: rust
      - name: Build wasm
        run: wasm-pack build --target nodejs --scope anonrig --out-dir out
        working-directory: rust
