name: rust test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Cargo Clippy
        run: cargo clippy
      - name: Cargo Format
        run: cargo fmt --check
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
