name: rust test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: cargo clippy
        working-directory: rust
      - name: Format
        run: cargo fmt --check
        working-directory: rust
      - name: Build
        run: cargo build --verbose
        working-directory: rust
      - name: Run tests
        run: cargo test --verbose
        working-directory: rust
      - name: Install wasm-pack
        run: cargo install wasm-pack
        working-directory: rust
      - name: Build wasm
        run: wasm-pack build --out-dir out
        working-directory: rust
