name: rust test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install wasm-pack
        run: cargo install wasm-pack
        working-directory: rust
      - name: Cargo Clippy
        run: cargo clippy
        working-directory: rust
      - name: Cargo Format
        run: cargo fmt --check
        working-directory: rust
      - name: Build
        run: cargo build
        working-directory: rust
      - name: Run tests
        run: cargo test
        working-directory: rust
      - name: Run wasm tests
        run: wasm-pack test --node
        working-directory: rust
      - name: Build wasm
        run: wasm-pack build --target nodejs --out-dir out
        working-directory: rust
      - name: Deploy
        run: |
          npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
          npm publish --access=public --tag=alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: rust/out
        if: ${{ github.ref == 'refs/heads/main' }}
